### PR TITLE
Desktop operator

### PR DESCRIPTION
**Pull request by pTivoli**
Problems:
-> Try catch not used/overwritten. (General)
-> The directories of the libraries must be changed/refused.
-> SeelItems: useless subquery on line 38, the indentifier of a drug is unique, there's no need to make another query for it
-> Timestamp: why calculating the right timestamp if there is (in postgreSQL) the current_timestamp function that return the current timestamp? Line 23,24,30,47 66-75
-> Class.forName() must be removed in every file (it doesn't work)
-> For each set of drugs there is only 1 receipt, problem on line: 45-48
-> SeelItems: useless subquery on line 53-57, the indentifier of a drug is unique, there's no need to make another query for it

### CODE REVIEW

**Comment by pTivoli** [comment]
-> The directories of the libraries must be changed/refused. SOLVED

**Comment by mMontinaro** [comment]
SOLVED:
SeelItems: useless subquery on line 38, the indentifier of a drug is unique, there's no need to make another query for it

**Comment by mMontinaro** [comment]
SOLVED:
Try catch not used/overwritten. (General)

**Comment by mMontinaro** [comment]
SOLVED:
-> Timestamp: why calculating the right timestamp if there is (in postgreSQL) the current_timestamp function that return the current timestamp? Line 23,24,30,47 66-75

**Comment by mMontinaro** [comment]
SOLVED:
For each set of drugs there is only 1 receipt, problem on line: 45-48

**Comment by mMontinaro** [comment]
SOLVED:
SeelItems: useless subquery on line 53-57, the indentifier of a drug is unique, there's no need to make another query for it

**Pull request merged**
